id: IA1A0A007
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-30T18:35:19.678615'
last_modified: '2022-05-30T18:35:19.678620'
parser: null
source_metadata:
  title: Dezhung Rinpoche Series
  language: bo
  description: 'Texts by and about Dezhung Rinpoche (sde gzhung rin po che, 1906–1987),
    one of the most important Sakya teachers of recent times renowned for his exceptional
    erudition and nonsectarianism:'
  volume:
    f207A:
      title: Aspiration for the Long Life of Dezhung Rinpoche (Jampa Kunga Tenpé Nyima)
      base_file: f207A.txt
      order: 1
      parent: Long Life Prayers
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
